---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: content/site-metadata.md
  label: Метаданные
- type: document
  path: content/header.md
  label: Шапка
- type: document
  path: content/navigation.md
  label: Навигация
- type: document
  path: content/landing-page.md
  label: Лендинг
- type: directory
  path: content/templated-pages
  label: Страницы
  create: all
  match: "**/*"
- type: document
  path: content/footer.md
  label: Подвал
upload_dir: public/static
public_path: "/static"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: out
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
